### ISSUE TITLE
Footer: espacio en el footer en pantallas de 1366x768.

### ISSUE THREAD

**Issue by LUIEMILIO20202020** [Darlin-code/nintaisquare#5]
![image](https://github.com/Darlin-code/nintaisquare/assets/157602796/c61cb378-6786-4c7c-b7b0-75485cf62239)

**Comment by drlncode** [comment]
Bug solucionado. -> [Commit.](https://github.com/Darlin-code/nintaisquare/commit/e5bb6d2edefb2b34bb2f0361fca8b44da3039846)
